project_name: Cosmos Relayer

builds:
  - id: darwin-amd64
    main: ./main.go
    binary: golang-cross
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/cosmos/relayer/v2/cmd.Version={{ .Tag }}
  - id: darwin-arm64
    main: ./main.go
    binary: golang-cross
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/arm64
      - PKG_CONFIG_PATH=/sysroot/macos/arm64/usr/local/lib/pkgconfig
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/cosmos/relayer/v2/cmd.Version={{ .Tag }}
  - id: linux-amd64
    main: ./main.go
    binary: golang-cross
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/cosmos/relayer/v2/cmd.Version={{ .Tag }}
  - id: linux-arm64
    main: ./main.go
    binary: golang-cross
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - CGO_CFLAGS=--sysroot=/sysroot/linux/
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/aarch64
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/aarch64
      - PKG_CONFIG_PATH=/sysroot/linux/aarch64/opt/vc/lib/pkgconfig:/sysroot/linux/aarch64/usr/lib/aarch64-linux-gnu/pkgconfig:/sysroot/linux/aarch64/usr/lib/pkgconfig:/sysroot/linux/aarch64/usr/local/lib/pkgconfig
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/cosmos/relayer/v2/cmd.Version={{ .Tag }}

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

release:
  prerelease: auto
  draft: true
